url: "https://getkiss.org"
description: An independent Linux® distribution with a focus on simplicity and the concept of "less is more". The distribution currently targets the x86-64 architecture and the English language.
author: "Dylan Araps"
permalink: pretty
theme:
syntax_highlighter: none
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter_opts:
        disable : true
compress_html:
    clippings: all
    comments: all
    endings: all
    startings: [html, head, body]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
include:
  - _redirects
  - sitemap.xml
