url: "https://getkiss.org"
permalink: pretty
theme:
plugins:
  - jekyll-sitemap
  - jekyll-feed
syntax_highlighter: none
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter_opts:
        disable : true
compress_html:
    clippings: all
    comments: all
    endings: all
    startings: [html, head, body]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
include:
  - _redirects
feed:
  categories:
    - news
